Rename migration file so migrating works
Without this name change, running `db:migrate` generates the error:

```
Caused by:
NameError: uninitialized constant Wages
```